#!/bin/sh
if [ $# -ne "1" ]; then
	echo "Specify a version!"
	exit 1;
fi

# Remove old binaries from debian/usr...
rm -f debian/usr/lib/libc64-emulator*

# Copy binaries to debian/usr/...
cp ../c64-emulator-lib-build-desktop/libc64-emulator.so.1.0.0 debian/usr/lib

# Clear executable bit 
chmod 644 debian/usr/lib/libc64-emulator.so.1.0.0

# Create library symlinks
( cd debian/usr/lib; ln -s libc64-emulator.so.1.0.0 libc64-emulator.so.1 )

# Update version in debian/DEBIAN/control
VERSION=$1
sed -e s/\<version\>/$VERSION/ debian-control > debian/DEBIAN/control

# Update MD5 sums in debian/DEBIAN/md5sums
( cd debian; md5sum `find usr -type f`) > debian/DEBIAN/md5sums

# Correct control file permissions
chmod 644 debian/DEBIAN/control debian/DEBIAN/md5sums

# Make debian
fakeroot dpkg-deb --build debian

# Rename
cp debian.deb libc64-emulator_$VERSION-1_i386.deb

# Lintian
lintian libc64-emulator_$VERSION-1_i386.deb

