#ifndef CDESIGNERCOMMON_H
#define CDESIGNERCOMMON_H

// Undo/redo stack
#define ATTRIBUTE_TABLE_CHAGE_COLOR_COMMAND 0x100000
#define TILE_STAMP_PAINT_COMMAND 0x110000
#define TILE_STAMP_RESIZE_COMMAND 0x110001

#define PIXELS_PER_TILESLICE 8
#define PIXEL_TO_TILE(pix) ((pix)/PIXELS_PER_TILESLICE)
#define PIXELS_PER_ATTRSECTION 16
#define PIXEL_TO_ATTRSECTION(pixx,pixy) ((((pixx)%PIXELS_PER_ATTRQUAD)/PIXELS_PER_ATTRSECTION)+((((pixy)%PIXELS_PER_ATTRQUAD)/PIXELS_PER_ATTRSECTION)<<1))
#define PIXELS_PER_ATTRQUAD 32
#define PIXEL_TO_ATTRQUAD(pix) ((pix)/PIXELS_PER_ATTRQUAD)

#endif // CDESIGNERCOMMON_H
