//    NESICIDE - an IDE for the 8-bit NES.
//    Copyright (C) 2009  Christopher S. Pow

//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the GNU General Public License as published by
//    the Free Software Foundation, either version 3 of the License, or
//    (at your option) any later version.

//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY; without even the implied warranty of
//    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//    GNU General Public License for more details.

//    You should have received a copy of the GNU General Public License
//    along with this program.  If not, see <http://www.gnu.org/licenses/>.

#include "cnesmappers.h"
#include "cnesrom.h"
#include "cnesrommapper001.h"
#include "cnesrommapper002.h"
#include "cnesrommapper003.h"
#include "cnesrommapper004.h"
#include "cnesrommapper005.h"
#include "cnesrommapper007.h"
#include "cnesrommapper009.h"
#include "cnesrommapper010.h"
#include "cnesrommapper011.h"
#include "cnesrommapper013.h"
#include "cnesrommapper028.h"
#include "cnesrommapper033.h"
#include "cnesrommapper034.h"
#include "cnesrommapper065.h"
#include "cnesrommapper068.h"
#include "cnesrommapper069.h"
#include "cnesrommapper075.h"

MapperFuncs mapperfunc[] =
{
   /* 000 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 001 */ { CROMMapper001::RESET, CROMMapper001::MAPPER, CROMMapper001::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROMMapper001::SYNCCPU, CROM::LATCH, CROMMapper001::LOAD, CROMMapper001::SAVE, true, true },
   /* 002 */ { CROMMapper002::RESET, CROMMapper002::MAPPER, CROMMapper002::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper002::LOAD, CROMMapper002::SAVE, true, false },
   /* 003 */ { CROMMapper003::RESET, CROMMapper003::MAPPER, CROMMapper003::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper003::LOAD, CROMMapper003::SAVE, false, true },
   /* 004 */ { CROMMapper004::RESET, CROMMapper004::MAPPER, CROMMapper004::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROMMapper004::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper004::LOAD, CROMMapper004::SAVE, true, true },
   /* 005 */ { CROMMapper005::RESET, CROMMapper005::MAPPER, CROM::MAPPER, CROMMapper005::LMAPPER, CROMMapper005::LMAPPER, CROMMapper005::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper005::LOAD, CROMMapper005::SAVE, true, true },
   /* 006 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 007 */ { CROMMapper007::RESET, CROMMapper007::MAPPER, CROMMapper007::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper007::LOAD, CROMMapper007::SAVE, true, false },
   /* 008 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 009 */ { CROMMapper009::RESET, CROMMapper009::MAPPER, CROMMapper009::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROMMapper009::LATCH, CROMMapper009::LOAD, CROMMapper009::SAVE, true, true },
   /* 010 */ { CROMMapper010::RESET, CROMMapper010::MAPPER, CROMMapper010::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROMMapper010::LATCH, CROMMapper010::LOAD, CROMMapper010::SAVE, true, true },
   /* 011 */ { CROMMapper011::RESET, CROMMapper011::MAPPER, CROMMapper011::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper011::LOAD, CROMMapper011::SAVE, true, true },
   /* 012 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 013 */ { CROMMapper013::RESET, CROMMapper013::MAPPER, CROMMapper013::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, true },
   /* 014 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 015 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 016 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 017 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 018 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 019 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 020 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 021 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 022 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 023 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 024 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 025 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 026 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 027 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 028 */ { CROMMapper028::RESET, CROMMapper028::MAPPER, CROMMapper028::MAPPER, CROMMapper028::LMAPPER, CROMMapper028::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, true, true },
   /* 029 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 030 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 031 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 032 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 033 */ { CROMMapper033::RESET, CROMMapper033::MAPPER, CROMMapper033::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper033::LOAD, CROMMapper033::SAVE, true, true },
   /* 034 */ { CROMMapper034::RESET, CROMMapper034::MAPPER, CROMMapper034::MAPPER, CROMMapper034::LMAPPER, CROMMapper034::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper034::LOAD, CROMMapper034::SAVE, true, true },
   /* 035 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 036 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 037 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 038 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 039 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 040 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 041 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 042 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 043 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 044 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 045 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 046 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 047 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 048 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 049 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 050 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 051 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 052 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 053 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 054 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 055 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 056 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 057 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 058 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 059 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 060 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 061 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 062 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 063 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 064 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 065 */ { CROMMapper065::RESET, CROMMapper065::MAPPER, CROMMapper065::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROMMapper065::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper065::LOAD, CROMMapper065::SAVE, true, true },
   /* 066 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 067 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 068 */ { CROMMapper068::RESET, CROMMapper068::MAPPER, CROMMapper068::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper068::LOAD, CROMMapper068::SAVE, true, true },
   /* 069 */ { CROMMapper069::RESET, CROMMapper069::MAPPER, CROMMapper069::MAPPER, CROMMapper069::LMAPPER, CROMMapper069::LMAPPER, CROM::SYNCPPU, CROMMapper069::SYNCCPU, CROM::LATCH, CROMMapper069::LOAD, CROMMapper069::SAVE, true, true },
   /* 070 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 071 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 072 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 073 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 074 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false },
   /* 075 */ { CROMMapper075::RESET, CROMMapper075::MAPPER, CROMMapper075::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROMMapper075::LOAD, CROMMapper075::SAVE, true, true },
   /* */
   /* 255 */ { CROM::RESET, CROM::MAPPER, CROM::MAPPER, CROM::LMAPPER, CROM::LMAPPER, CROM::SYNCPPU, CROM::SYNCCPU, CROM::LATCH, CROM::LOAD, CROM::SAVE, false, false }
};
